### ISSUE TITLE
Why StarPU doesn't release the memory

### ISSUE THREAD

**Issue by SulleyZhou** [starpu-runtime/starpu#29]
Dear StarPU developers :
When I run the stencil5_starpu.c program with the arguments of iter=100 and size=1000, my memory is full by the data. However, the memory is not released when the program ended. I wonder why!

**Comment by sthibaul** [comment]
How do you observe the memory use?

**Comment by nfurmento** [comment]
In the future, i would strongly advise to follow the guideline when submitting an issue, it allow everyone to gain time in understanding what the issue is about.
https://github.com/starpu-runtime/starpu/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

**Comment by nfurmento** [comment]
closing the issue as it seems to have resolved on its own
