### ISSUE TITLE
support for MPI data count larger than INT_MAX

### ISSUE THREAD

**Issue by JieRen98** [starpu-runtime/starpu#43]
**Is your feature request related to a problem? Please describe.**
Since MPI uses int32 as the data count, see as follows
```C
int MPI_Send(const void *buf, int count, MPI_Datatype datatype, int dest,
             int tag, MPI_Comm comm)
```
When we want to send a larger buffer (count > INT_MAX), we need to split the buffer into several chunks and send them one by one. However, StarPU does not support it so far. (e.g., https://gitlab.inria.fr/starpu/starpu/-/blob/master/src/drivers/mpi/driver_mpi_common.c?ref_type=heads#L300)

**Describe the solution you'd like**
Split the buffer into several chunks:
```C
void send_large_byte_buffer(const void* data, size_t total_size, int dest, int tag, MPI_Comm comm) {
    const size_t max_int = INT_MAX;
    size_t chunks = (total_size + max_int - 1) / max_int;

    for (size_t i = 0; i < chunks; ++i) {
        const size_t offset = i * max_int;
        const int count = (total_size - offset) > max_int ? max_int : (int)(total_size - offset);

        MPI_Send((const char*)data + offset, count, MPI_BYTE, dest, tag, comm);
    }
}
```

Functions' signatures (e.g., [__starpu_mpi_common_send_to_device](https://gitlab.inria.fr/starpu/starpu/-/blob/master/src/drivers/mpi/driver_mpi_common.c?ref_type=heads#L265), [__starpu_mpi_common_send](https://gitlab.inria.fr/starpu/starpu/-/blob/master/src/drivers/mpi/driver_mpi_common.c?ref_type=heads#L221), etc) should be changed correspondingly.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sthibaul** [comment]
> StarPU does not support it so far. (e.g., https://gitlab.inria.fr/starpu/starpu/-/blob/master/src/drivers/mpi/driver_mpi_common.c?ref_type=heads#L300)

I guess you are using `starpu_mpi_task_insert` etc., not the MPI master-slave driver support, so it's rather the MPI datatype definition from `mpi/src/starpu_mpi_datatype.c` that you need fixed.

I understand that you have a urgent deadline. Which StarPU data type are you  using in your application?

**Comment by JieRen98** [comment]
Greetings,

I am using Chameleon actually. I am not completely sure how Chaneleon
interact with StarPU. I am going to use multiple precisions (FP64, FP32,
FP16, and FP8).

Best,
Jie

Samuel Thibault ***@***.***>于2024年4月8日 周一14:25写道：

**Comment by sthibaul** [comment]
> I am using Chameleon actually. I am not completely sure how Chaneleon interact with StarPU

Ok, then I guess you are using a matrix descriptor from Chameleon?

**Comment by JieRen98** [comment]
Yes, specifically, my customized descriptor.

Samuel Thibault ***@***.***>于2024年4月8日 周一14:31写道：

**Comment by sthibaul** [comment]
How is it customized? Essentially, the question is which `starpu_data_something_register` function is getting called in your case.

**Comment by sthibaul** [comment]
put another way, do you have any `data_register` call beyond `starpu_vector_data_register` and `starpu_mpi_data_register`?

Is it using `starpu_data_register` directly?

**Comment by sthibaul** [comment]
Does it use `starpu_mpi_interface_datatype_register`?

**Comment by JieRen98** [comment]
Sorry I am having my lunch, I will answer your question about 20mins later.

Samuel Thibault ***@***.***>于2024年4月8日 周一14:46写道：

**Comment by sthibaul** [comment]
Is `MPI_Type_vector_c` supported by your mpi implementation?

**Comment by sthibaul** [comment]
(basically, we would just want to use the `_c` variants of the MPI calls that we currently make: `MPI_Irecv`, `MPI_Isend`, `MPI_Issend`, `MPI_Type_vector`, `MPI_Type_contiguous`, `MPI_Type_size`)

**Comment by sthibaul** [comment]
Then it must be also using `starpu_mpi_interface_datatype_register` to register the mpi type to be used? Otherwise StarPU does not even know the size count in bytes.

**Comment by sthibaul** [comment]
Please also show `cti_allocate_datatype_node` and `cti_allocate_datatype`, that's very most probably where you need a fix

**Comment by JieRen98** [comment]
Here you go:
```c
#if defined(CHAMELEON_USE_MPI_DATATYPES)
int
cti_allocate_datatype_node( starpu_data_handle_t handle,
                            unsigned             node,
                            MPI_Datatype        *datatype )
{
    int ret;

    starpu_cham_tile_interface_t *cham_tile_interface = (starpu_cham_tile_interface_t *)
        starpu_data_get_interface_on_node( handle, node );

    size_t m  = cham_tile_interface->tile.m;
    size_t n  = cham_tile_interface->tile.n;
    size_t ld = cham_tile_interface->tile.ld;
    size_t elemsize = CHAMELEON_Element_Size( cham_tile_interface->flttype );

    ret = MPI_Type_vector( n, m * elemsize, ld * elemsize, MPI_BYTE, datatype );
    STARPU_ASSERT_MSG(ret == MPI_SUCCESS, "MPI_Type_vector failed");

    ret = MPI_Type_commit( datatype );
    STARPU_ASSERT_MSG(ret == MPI_SUCCESS, "MPI_Type_commit failed");

    return 0;
}

int
cti_allocate_datatype( starpu_data_handle_t handle,
                       MPI_Datatype        *datatype )
{
    return cti_allocate_datatype_node( handle, STARPU_MAIN_RAM, datatype );
}

void
cti_free_datatype( MPI_Datatype *datatype )
{
    MPI_Type_free( datatype );
}
#endif
```

**Comment by sthibaul** [comment]
> Here you go:
> 
> ```c
>     ret = MPI_Type_vector( n, m * elemsize, ld * elemsize, MPI_BYTE, datatype );
> ```

That's it: you want to use `MPI_Type_vector_c` instead. StarPU just MPI_Sends one of this type.

**Comment by JieRen98** [comment]
> > Here you go:
> > ```c
> >     ret = MPI_Type_vector( n, m * elemsize, ld * elemsize, MPI_BYTE, datatype );
> > ```
> 
> That's it: you want to use `MPI_Type_vector_c` instead. StarPU just MPI_Sends one of this type.

Ok, Chameleon uses `byte` and the leading dim becomes `ld * sizeof(t)`, that's fine I guess. So do you mean I should change this to MPI_Type_vector_c to support large integers?

**Comment by sthibaul** [comment]
If your MPI implementation supports `MPI_Type_vector_c`, that's the simplest, yes. If not, you need to use a for loop to describe the data type piece by piece.

**Comment by JieRen98** [comment]
> > > MPI_Type_vector_c
> > 
> > 
> > I didn't find any line includes `MPI_Type_vector_c`
> 
> Where did you not find it?
> 
> Put another way: which MPI implementation are you using?

I am using mpich, I mean Chameleon does not use `MPI_Type_vector_c`, not my MPI does not have this.

**Comment by sthibaul** [comment]
So in the end it's the chameleon code that needs fixing. StarPU will however want to do the same for its predefined vector/matrix/etc. types, so keeping this issue open for that.

**Comment by sthibaul** [comment]
> I am using mpich

mpich does have `MPI_Type_vector_c`, so you can simply add a `_c` to the `MPI_Type_vector` call, and that should work.

**Comment by sthibaul** [comment]
(mpich does so apparently since its version 4)

**Comment by JieRen98** [comment]
Thanks a lot! I was reading StarPU, but it seems that I did not do well. So `starpu_mpi_interface_datatype_node_register` is the most important thing. While the `starpu_data_register` and `starpu_mpi_data_register` calls have no effect on the integer overflow, if `allocate_datatype_func` is correctly defined (using `MPI_Type_vector_c`) in calling `starpu_mpi_interface_datatype_node_register`?

**Comment by JieRen98** [comment]
Thanks a lot, you helped a lot!
