### ISSUE TITLE
Incorrect installation instructions

### ISSUE THREAD

**Issue by athas** [starpu-runtime/starpu#53]
I am trying to install StarPU via the starpu-nightly-latest.tar.gz tarball (unpacks to starpu-1.4.7.99) via the instructions in the README. However, these instructions seem wrong:

```
$ mkdir build && cd build
$ ./configure
$ make
$ make install
```

If I createa a new `build` directory and immediately `cd` into it, then there is no way it can contain a `configure` script.

**Comment by nfurmento** [comment]
Thanks, i just fixed the configure call.

The update will be available in github tomorrow.
